import os
play = 'y'

while play == ('y') or play == ('Y'):
  os.system('clear')
  print("Welcome to My Mad Libs")
  print("Which Passage Would You Like to Select?\n")

  print("1: Thanksgiving Themed Passage")
  print("2: National Anthem Themed Passage")
  print("3: Christmas Letter to Santa")
  selection = input()
  if selection == ("1"):
    adjective1 = input("Enter an Adjective: ")
    adjective2 = input("Enter an Adjective: ")
    bird = input("Enter a Type of Meat: ")
    noun1 = input("Enter a Room in a House: ")
    verb1 = input("Enter a Past Tense Verb: ")
    verb2 = input("Enter a Verb: ")
    noun2 = input("Enter a Relative's Name: ")
    noun3 = input("Enter a Noun: ")
    noun4 = input("Enter a Liquid: ")
    verb3 = input("Enter a Verb ending in -ing: ")
    noun5 = input("Enter a Part of the Body (Plural): ")
    noun6 = input("Enter a Plural Noun: ")
    verb4 = input("Enter a Verb Ending in -ing: ")
    noun7 = input("Enter a Noun: ")
    print("\nHere is Your Prompt... \n")
    print("It was a " + adjective1 + ", cold November night. I woke up to the " + adjective2 + " smell of " + bird + " roasting in the " + noun1 + ". I " + verb1 + " down the stairs to see if I could help " + verb2 + " the dinner. Mom said, 'See if " + noun2 + " needs a fresh " + noun3 + "'. So I carried a tray of glasses full of " + noun4 + " into the " + verb3 + " room. When I got there, I couldn't believe my " + noun5 + "! There were " + noun6 + " " + verb4 + " on the " + noun7 + "!"  ) 

  if selection == ("2"):
    verb1 = input("Enter a Type of Verb: ")
    noun1 = input("Enter a Type of Noun: ")
    adverb1 = input("Enter a Type of Adverb: ")
    verb2 = input("Enter a Past Tense Verb: ")
    noun2 = input("Enter a Plural Noun: ")
    noun3 = input("Enter a Plural Noun: ")
    adjective1 = input("Enter an Adjective: ")
    noun4 = input("Enter a Plural Noun: ")
    verb3 = input("Enter a Verb Ending in -ing: ")
    noun5 = input("Enter a Color: ")
    noun6 = input("Enter a Plural Noun: ")
    noun7 = input("Enter a Noun: ")
    noun8 = input("Enter a Noun: ")
    interjection1 = ("Enter an Interjection: ")
    adjective2 = ("Enter an Adjective: ")
    verb4 = ("Enter a Verb: ")
    adjective3 = input("Enter an Adjective: ")
    adjective4 = input("Enter an Adjective: ")
    print("\nO' say can you " + verb1 + " by the dawn's early " + noun1 + ". What so " + adverb1 + " we " + verb2 + " at the twighlight's last gleaming. Whos broad " + noun2 + " and bright " + noun3 + " through the " + adjective1 + " fight. O'er the " + noun4 + " we watched, were so gallantly " + verb3 + " and the rocket's " + noun5 + " glare, the " + noun6 + " bursting in " + noun7 + ". Gave proof, through the night, that our " + noun8 + " was still there; " + interjection1 + " does that " + adjective2 + " banner yet " + verb4 + ". O'er the land of the " + adjective3 + " and the home of the " + adjective4)
  if selection == ("3"): 
    noun1 = input("Enter a Name: ")
    noun2 = input("Enter a Number: ")
    noun3 = input("Enter Another Number: ")
    noun4 = input("Enter ANOTHER Number: ")
    noun5 = input("Enter an Animal: ")
    noun6 = input("Enter Another Animal:")
    noun7 = input("Enter a State: ")
    adjective1 = input("Enter an Adjective: ")
    adjective2 = input("Enter an Adjective: ")
    adjective3 = input("Enter an Adjective Ending in -er: ")
    noun8 = input("Enter a Place: ")
    noun9 = input("Enter the Name of a Family Member: ")
    adjective4 = input("Enter an Adjective: ")
    noun10 = input("Enter a Number: ")
    noun11 = input("Enter a Noun: ")
    verb1 = input("Enter a Verb: ")
    noun12 = input("Enter a Noun: ")
    noun13 = input("Enter a Language: ")
    adjective5 = input("Enter an Adjective: ")
    adjective6 = input("Enter Another Adjective: ")
    noun14 = input("Enter a Noun: ")
    noun15 = input("Enter a Noun: ")
    noun16 = input("Enter a Food (Plural): ")
    noun17 = input("Enter a Drink: ")
    noun18 = input("Enter a Food (Plural): ")
    adjective7 = input("Enter an Adjective: ")
    print("Dear Santa. My name is " + noun1 + " and I am " + noun2 + " years old. I have " + noun3 + " brothers, " + noun4 + " sisters, a " + noun5 + ", and a " + noun6 + ". I live in " + noun7 + ". When I woke up in the morning it was " + adjective1 + " and " + adjective2 + "outisde. It must be much  " + adjective3 + " where you live in " + noun8 + "! My " + noun9 + " said I have been a very " + adjective4 + " (boy/ girl) this year, so I will ask you for " + noun10 + " gifts for Christmas. I would like a " + noun11 + " that can " + verb1 + ", and a " + noun12 + " that speaks " + noun13 + ". If you think I've been extra " + adjective5 + " this year, I would like a " + adjective6 + " " + noun14 + " too. When you come down the " + noun15 + " at our house on Christmas Eve, we will have " + noun16 + " and " + noun17 + " waiting for you! I hope you like them! We will also leave out some " + noun18 + " for the reindeer! Have a " + adjective7 + " flight!")

  print("\nWould you like to play again? (y) or (n)")
  play = input('')